ProductsBundle\Entity\Products:
    type: entity
    table: products
    indexes:
        fk_products_categories_idx:
            columns:
                - idcategories
    id:
        idproduct:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        code:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        name:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        description:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        brand:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        price:
            type: float
            nullable: false
            precision: 10
            scale: 0
    manyToOne:
        idcategories:
            targetEntity: Categories
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                idcategories:
                    referencedColumnName: idcategories
            orphanRemoval: false
    lifecycleCallbacks: {  }
