homepage:
    path:     /
    defaults: { _controller: ProductsBundle:Home:index }

products_add:
    path:     /products/add
    defaults: { _controller: ProductsBundle:Products:add }
    
products_index:
    path:     /products/index
    defaults: { _controller: ProductsBundle:Products:index }
    
products_edit:
    path:     /products/edit/{id}
    defaults: { _controller: ProductsBundle:Products:edit }
    
products_delete:
    path:     /products/delete/{id}
    defaults: { _controller: ProductsBundle:Products:delete }

categories_add:
    path:     /categories/add
    defaults: { _controller: ProductsBundle:Categories:add }
    
categories_index:
    path:     /categories/index
    defaults: { _controller: ProductsBundle:Categories:index }
    
categories_edit:
    path:     /categories/edit/{id}
    defaults: { _controller: ProductsBundle:Categories:edit }
    
categories_delete:
    path:     /categories/delete/{id}
    defaults: { _controller: ProductsBundle:Categories:delete }